const multi_lang_object = {
    "uiName": {
        "switchLanguageButton": ["中文", "Eng"],
        "saved-stop": ["Saved Stop: ", "已儲存車站: "],
        "editShortcutButton": ["Edit", "管理"]
    },
    "dataText": {
        "lastUpdate": ["Last Update", "最後更新"],
        "statusString": ["Status: Error / Alert", "狀態: 錯誤 / 警告"],
        "route_no": ["Route No.", "路線"],
        "dest": ["Destination", "往"],
        "train_length": ["Train Length", "車廂數"],
        "time": ["Estimated Time", "預計時間"],
        "isInService": ["In Service", "服務中"],
        "networkError": ["Network error. Please check your network connection.", "網路錯誤，請檢查你的網路連線。"],
        "internalServerError": ["Internal server error. Please try again later.", "伺服器錯誤，請稍後再試。"],
        "tooManyRequests": ["Too many requests. Please try again later.", "發出太多請求，請稍後再試。"],
        "unknownError": ["Unknown error. Please try again later.", "發生未知錯誤，請稍後再試。"]
    },
    "station_id": {
        "1": ["Tuen Mun Ferry Pier", "屯門碼頭"],
        "10": ["Melody Garden", "美樂"],
        "15": ["Butterfly", "蝴蝶"],
        "20": ["Light Rail Depot", "輕鐵車廠"],
        "30": ["Lung Mun", "龍門"],
        "40": ["Tsing Shan Tsuen", "青山村"],
        "50": ["Tsing Wun", "青雲"],
        "60": ["Kin On", "建安"],
        "70": ["Ho Tin", "河田"],
        "75": ["Choy Yee Bridge", "蔡意橋"],
        "80": ["Affluence", "澤豐"],
        "90": ["Tuen Mun Hospital", "屯門醫院"],
        "100": ["Siu Hong", "兆康"],
        "110": ["Kei Lun", "麒麟"],
        "120": ["Ching Chung", "青松"],
        "130": ["Kin Sang", "建生"],
        "140": ["Tin King", "田景"],
        "150": ["Leung King", "良景"],
        "160": ["San Wai", "新圍"],
        "170": ["Shek Pai", "石排"],
        "180": ["Shan King (North)", "山景(北)"],
        "190": ["Shan King (South)", "山景(南)"],
        "200": ["Ming Kum", "鳴琴"],
        "212": ["Tai Hing (North)", "大興(北)"],
        "220": ["Tai Hing (South)", "大興(南)"],
        "230": ["Ngan Wai", "銀圍"],
        "240": ["Siu Hei", "兆禧"],
        "250": ["Tuen Mun Swimming Pool", "屯門泳池"],
        "260": ["Goodview Garden", "豐景園"],
        "265": ["Siu Lun", "兆麟"],
        "270": ["On Ting", "安定"],
        "275": ["Yau Oi", "友愛"],
        "280": ["Town Centre", "市中心"],
        "295": ["Tuen Mun", "屯門"],
        "300": ["Pui To", "杯渡"],
        "310": ["Hoh Fuk Tong", "何福堂"],
        "320": ["San Hui", "新墟"],
        "330": ["Prime View", "景峰"],
        "340": ["Fung Tei", "鳳地"],
        "350": ["Lam Tei", "藍地"],
        "360": ["Nai Wai", "泥圍"],
        "370": ["Chung Uk Tsuen", "鍾屋村"],
        "380": ["Hung Shui Kiu", "洪水橋"],
        "390": ["Tong Fong Tsuen", "塘坊村"],
        "400": ["Ping Shan", "屏山"],
        "425": ["Hang Mei Tsuen", "坑尾村"],
        "430": ["Tin Shui Wai", "天水圍"],
        "435": ["Tin Tsz", "天慈"],
        "445": ["Tin Yiu", "天耀"],
        "448": ["Locwood", "樂湖"],
        "450": ["Tin Wu", "天湖"],
        "455": ["Ginza", "銀座"],
        "460": ["Tin Shui", "天瑞"],
        "468": ["Chung Fu", "頌富"],
        "480": ["Tin Fu", "天富"],
        "490": ["Chestwood", "翠湖"],
        "500": ["Tin Wing", "天榮"],
        "510": ["Tin Yuet", "天悅"],
        "520": ["Tin Sau", "天秀"],
        "530": ["Wetland Park", "濕地公園"],
        "540": ["Tin Heng", "天恒"],
        "550": ["Tin Yat", "天逸"],
        "560": ["Shui Pin Wai", "水邊圍"],
        "570": ["Fung Nin Road", "豐年路"],
        "580": ["Hong Lok Road", "康樂路"],
        "590": ["Tai Tong Road", "大棠路"],
        "600": ["Yuen Long", "元朗"],
        "920": ["Sam Shing", "三聖"],
    }
}